// Ambient type declarations for the web workspace.
//
// We duplicate Next.js's `*.svg` module declaration here (normally supplied
// by `/// <reference types="next/image-types/global" />` inside next-env.d.ts)
// because next-env.d.ts is git-ignored and auto-generated by `next dev` /
// `next build`. CI runs `tsc --noEmit` BEFORE `next build`, so next-env.d.ts
// doesn't exist yet and typecheck fails to resolve imports like
// `@focrel/brand/assets/logo.svg` (TS2307).
//
// Keeping this declaration local means typecheck is self-sufficient and CI
// order doesn't matter.

declare module "*.svg" {
  const content: {
    src: string;
    width: number;
    height: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
  };
  export default content;
}
